name: 'Bump version and update GoDev'

on:
  push:
    branches: [master]
    paths: ['version']
      
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create tag
        id: create_tag
        run: |
          tag=$(cat version)
          echo ::set-output name=tag::$tag
      - run: |
          git tag v${{ steps.create_tag.outputs.tag }}
          git push origin v${{ steps.create_tag.outputs.tag }}

  list-on-godev:
    runs-on: ubuntu-latest
    needs: [create-tag]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Create tag
        id: create_tag
        run: |
          tag=$(cat version)
          echo ::set-output name=tag::$tag
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
      - name: List 
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/jodios/ebitentextureunpacker@v${{ steps.create_tag.outputs.tag }}
